const cards = [
  { word: "Anchor", taboo: ["vessel", "rope", "move"] },
  { word: "Bow", taboo: ["ship", "front", "part"] },
  { word: "Bridge Room", taboo: ["captain", "rudder", "observe"] },
  { word: "Cabin", taboo: ["room", "bed", "rest"] },
  { word: "Cadet", taboo: ["training", "student", "naval"] },
  { word: "Captain", taboo: ["ship", "leader", "sailor"] },
  { word: "Cargo", taboo: ["goods", "transport", "carry"] },
  { word: "Cargo Handling", taboo: ["load", "unload", "transport"] },
  { word: "Chart", taboo: ["map", "sea", "navigation"] },
  { word: "Compass", taboo: ["tool", "direction", "south"] },
  { word: "Crane", taboo: ["Lift", "heavy", "machine"] },
  { word: "Crew", taboo: ["team", "ship", "officers"] },
  { word: "Cruise", taboo: ["luxury", "passengers", "huge"] },
  { word: "Deck", taboo: ["floor", "outside", "walk"] },
  { word: "Depth", taboo: ["deep", "water", "bottom"] },
  { word: "Drill", taboo: ["equipment", "hole", "activity"] },
  { word: "Funnel", taboo: ["smoke", "ship", "pipe"] },
  { word: "Galley", taboo: ["kitchen", "eat", "sit"] },
  { word: "Gangway", taboo: ["walk", "bridge", "vessel"] },
  { word: "Harbor", taboo: ["boat", "water", "city"] },
  { word: "Hatch cover", taboo: ["ship", "open", "cargo"] },
  { word: "Hold", taboo: ["crane", "cargo", "storage"] },
  { word: "Hook", taboo: ["vessel", "secure", "dock"] },
  { word: "Icebreaker", taboo: ["clear", "icy", "water"] },
  { word: "Lighthouse", taboo: ["light", "tower", "coast"] },
  { word: "Lightship", taboo: ["dangerous", "shore", "light"] },
  { word: "Logbook", taboo: ["important", "record", "ship"] },
  { word: "Machinery", taboo: ["machine", "engine", "equipment"] },
  { word: "Manoeuvre", taboo: ["move", "change", "course"] },
  { word: "Marine", taboo: ["sea", "ocean", "transport"] },
  { word: "Maritime Learners", taboo: ["student", "naval", "sea"] },
  { word: "Master", taboo: ["captain", "leader", "crew"] },
  { word: "Mooring", taboo: ["anchor", "boat", "tie"] },
  { word: "Nautical", taboo: ["ship", "marine", "sailors"] },
  { word: "Navigation", taboo: ["steer", "course", "direction"] },
  { word: "On-board", taboo: ["carry", "used", "vessel"] },
  { word: "Passage", taboo: ["travel", "ship", "journey"] },
  { word: "Periscope", taboo: ["submarine", "look", "above"] },
  { word: "Port", taboo: ["berth", "stop", "load/unload"] },
  { word: "Reefer", taboo: ["refrigerator", "carry", "fresh food"] },
  { word: "Regulations", taboo: ["rules", "follow", "order"] },
  { word: "Route", taboo: ["path", "map", "destination"] },
  { word: "Rudder", taboo: ["control", "steer", "direction"] },
  { word: "Sail", taboo: ["wind", "travel", "vessel"] },
  { word: "Seafarer", taboo: ["ship", "sea", "travel"] },
  { word: "Ship", taboo: ["boat", "sea", "transport"] },
  { word: "Ship Engineer", taboo: ["work", "sea", "fix", "head"] },
  { word: "Stability", taboo: ["sink", "balanced", "fixed"] },
  { word: "Starboard", taboo: ["right", "side", "ship"] },
  { word: "Stern", taboo: ["ship", "back", "part"] },
  { word: "Submarine", taboo: ["water", "ship", "deep"] },
  { word: "Tank", taboo: ["hold", "container", "ship"] },
  { word: "Tug", taboo: ["pull/push", "docking", "rope"] },
  { word: "Upkeep", taboo: ["repair", "maintenance", "operate"] },
  { word: "Volume", taboo: ["space", "size", "amount"] },
  { word: "Watchkeeping", taboo: ["on duty", "observe", "hours"] },
  { word: "Wave", taboo: ["water", "movement", "ocean"] },
];